### PR TITLE
build: use package.json to manage semrel and its deps

### PR DESCRIPTION
**Pull request by padamstx**
## PR summary
Adds package.json to manage semantic-release dependencies.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by dpopp07** [comment]
The `package.json` file seems to be missing 🙂

**Comment by padamstx** [comment]
> The `package.json` file seems to be missing slightly_smiling_face

Thank goodness someone is paying attention :joy: My mistake was I forgot to run `git add .` prior to committing :)

**Review by dpopp07 — APPROVED** [review]
👍

**Pull request merged**
