### PR TITLE
fix(test): fix flaky tests

### PR DESCRIPTION
**Pull request by ZhewenFu**
## PR summary

Fix two flaky tests under `modules/configuration-governance`.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

The current tests use `toString()` method to compare two json-like objects. Since the `toString()` method doesn't guarantee the ordering of objects, after deserializing the objects, the ordering of the string might change and the tests might fail. 
The new behavior simply checks those fields one by one to avoid the inconsistent ordering of strings. In this case, as long as the functionality of the two methods is correct, the tests would always pass after deserializing the objects.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by padamstx** [comment]
The two classes you modified are generated, not manually developed, so we really can't make manual changes since those changes would be overwritten the next time the code is re-generated.

Can you explain the conditions under which you saw the failures?  We have seen no such failures in all of our unit testing

**Comment by ZhewenFu** [comment]
> The two classes you modified are generated, not manually developed, so we really can't make manual changes since those changes would be overwritten the next time the code is re-generated.
> 
> Can you explain the conditions under which you saw the failures? We have seen no such failures in all of our unit testing

* The two classes you modified are generated, not manually developed, so we really can't make manual changes since those changes would be overwritten the next time the code is re-generated.

Thanks for letting me know! Is there any way to modify the test on the generator side? 

* Can you explain the conditions under which you saw the failures? We have seen no such failures in all of our unit testing
Yes, the test failed in certain cases but I didn't record down the conditions.  I detected that the test results are flaky using the NonDex tool for catching non-deterministic/flaky tests (https://github.com/TestingResearchIllinois/NonDex).

  You may reproduce the nondeterministic behavior using the following steps:
  Clone the repo and cd into it.
`mvn install -pl modules/configuration-governance -am -DskipTests`
`mvn -pl modules/configuration-governance test -Dtest=com.ibm.cloud.platform_services.configuration_governance.v1.model.RuleRequestTest#testRuleRequest`
`mvn -pl modules/configuration-governance edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.ibm.cloud.platform_services.configuration_governance.v1.model.RuleRequestTest#testRuleRequest`

**Comment by padamstx** [comment]
Yeah, I thought this sounded a little like that NonDex tool.  You guys took a run at us a time or two in the past.   Can you put this project on an opt-out list or something so that you don't keep opening up PRs that will just be closed?

**Comment by ZhewenFu** [comment]
> Yeah, I thought this sounded a little like that NonDex tool. You guys took a run at us a time or two in the past. Can you put this project on an opt-out list or something so that you don't keep opening up PRs that will just be closed?

Well unfortunately I cannot put it on an opt-out list since I am just a student taking this course which requires us to fix the tests detected by the NonDex tool. But I think you can definitely contact the professor in this case.

**Comment by ZhewenFu** [comment]
> Yeah, I thought this sounded a little like that NonDex tool. You guys took a run at us a time or two in the past. Can you put this project on an opt-out list or something so that you don't keep opening up PRs that will just be closed?

But I will definitely let the professor know this issue in the meanwhile.

**Pull request closed without merging**
