### PR TITLE
feat(Usage Reports): add "created_by_email_id" to Offer schema

### PR DESCRIPTION
**Pull request by Jdatechong**
## PR summary
updated offers to have the createdByEmailId field

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
updated offers to have the createdByEmailId field

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information
Test results:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] IBM Cloud Platform Services Java SDK 99-SNAPSHOT ... SUCCESS [ 13.308 s]
[INFO] IBM Cloud Platform Services SDK Common Library ..... SUCCESS [ 16.860 s]
[INFO] IBM Cloud Case Management API ...................... SUCCESS [ 27.011 s]
[INFO] IBM Cloud Catalog Management API ................... SUCCESS [ 38.860 s]
[INFO] IBM Cloud Context-Based Restrictions API ........... SUCCESS [ 26.569 s]
[INFO] IBM Cloud Enterprise Billing Units API ............. SUCCESS [ 21.871 s]
[INFO] IBM Cloud Enterprise Management API ................ SUCCESS [ 22.262 s]
[INFO] IBM Cloud Enterprise Usage Reports API ............. SUCCESS [ 25.420 s]
[INFO] IBM Cloud Global Catalog API ....................... SUCCESS [ 25.901 s]
[INFO] IBM Cloud Global Search and Tagging - Search API ... SUCCESS [ 22.200 s]
[INFO] IBM Cloud Global Search and Tagging - Tagging API .. SUCCESS [ 21.671 s]
[INFO] IBM Cloud IAM Access Groups API .................... SUCCESS [ 26.214 s]
[INFO] IBM Cloud IAM Identity Services API ................ SUCCESS [ 30.540 s]
[INFO] IBM Cloud IAM Policy Management API ................ SUCCESS [ 27.531 s]
[INFO] IBM Cloud Shell Account Settings API ............... SUCCESS [ 21.902 s]
[INFO] IBM Cloud Open Service Broker API .................. SUCCESS [ 22.493 s]
[INFO] Partner Billing Units .............................. SUCCESS [ 22.952 s]
[INFO] Partner Usage Reports .............................. SUCCESS [ 23.497 s]
[INFO] IBM Cloud Resource Controller API (v2) ............. SUCCESS [ 24.662 s]
[INFO] IBM Cloud Resource Manager API ..................... SUCCESS [ 23.276 s]
[INFO] IBM Cloud Usage Metering API ....................... SUCCESS [ 30.926 s]
[INFO] IBM Cloud Usage Reports API ........................ SUCCESS [ 55.411 s]
[INFO] IBM Cloud User Management API ...................... SUCCESS [ 22.741 s]
[INFO] IBM Cloud Platform Services Test Coverage Reports .. SUCCESS [  9.179 s]
[INFO] IBM Cloud Platform Services Code Examples 99-SNAPSHOT SUCCESS [ 15.598 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:19 min
[INFO] Finished at: 2024-09-09T12:42:40-07:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Review by pyrooka — APPROVED** [review]
Looks good! The only question I have is: have you signed the CLA?

**Review by pyrooka — CHANGES_REQUESTED** [review]
@Jdatechong Please re-gen the code by using the latest version of the generator. Thank you!

**Comment by pyrooka** [comment]
Is that the only file that has been updated after re-generating the project with the latest version of the generator. Just asking because the service file seems to still showing and older generator version, [see here](https://github.com/Jdatechong/platform-services-java-sdk/blob/main/modules/usage-reports/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReports.java#L15). Sorry for being too picky! :)

**Comment by Jdatechong** [comment]
> Is that the only file that has been updated after re-generating the project with the latest version of the generator. Just asking because the service file seems to still showing and older generator version, [see here](https://github.com/Jdatechong/platform-services-java-sdk/blob/main/modules/usage-reports/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReports.java#L15). Sorry for being too picky! :)

Sure, it should be updated in the latest commit. I didn't include a few other files since they just had 1 line changes with just changes to the copyright statement.

**Review by pyrooka — APPROVED** [review]
Looks good to me!

**Pull request merged**
