### PR TITLE
fix(Global Tagging): add 'update' option to attach_tag operation

### PR DESCRIPTION
**Pull request by fabrizio-leoni**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by fabrizio-leoni** [comment]
image

**Comment by fabrizio-leoni** [comment]
image

**Comment by fabrizio-leoni** [comment]
@padamstx I notidìced that in this repository the file pom.xmlthere contains a section with this tag `<jacoco-plugin-version>0.8.10</jacoco-plugin-version>` even if it seems wrong. The right version should be `0.8.11`

**Review by padamstx — APPROVED** [review]
LGTM

**Comment by padamstx** [comment]
> @padamstx I notidìced that in this repository the file pom.xml contains a section with this tag `<jacoco-plugin-version>0.8.10</jacoco-plugin-version>` even if it seems wrong. The right version should be `0.8.11` Do you prefer I will commit the file pom.xml the new jacoco-plugin version or not?

I can make that change after this PR is merged.

**Pull request merged**
