### PR TITLE
feat(Resource Controller): add "onetime_credentials" property in ResourceInstance and ResourceKey schemas

### PR DESCRIPTION
**Pull request by arshabbir**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pyrooka — CHANGES_REQUESTED** [review]
Changes are looking good so far, but please attach the result of the integration and examples test run.

**Comment by arshabbir** [comment]
[output_integration.txt](https://github.com/user-attachments/files/16164389/output_integration.txt)
[output_mvn_clean_UTs.txt](https://github.com/user-attachments/files/16164391/output_mvn_clean_UTs.txt)
[output_examples.txt](https://github.com/user-attachments/files/16164406/output_examples.txt)

**Review by pyrooka — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
